### ISSUE TITLE
Android 5 only ?

### ISSUE THREAD

**Issue by hervehobbes** [don/cordova-plugin-hce#4]
Hello,

Is this plugin running with Android 5 "only"?

bye

**Comment by don** [comment]
It probably needs updated permissions to work with Android 6. The work around would be to target android-22 by modifying the config.xml.

```
<preference name="android-targetSdkVersion" value="22"/> 
```

**Comment by hervehobbes** [comment]
Hello,

In fact I was talking of Android 4 ;-)

**Comment by don** [comment]
HCE APIs were added with android-19 (KITKAT) so it should work with 4.4.
