### ISSUE TITLE
Android card reader application example in cordova

### ISSUE THREAD

**Issue by leftdead7** [don/cordova-plugin-hce#9]
Hii don
by any chance do you happen to have a cordova version of the card reader example mentioned in the docs?
or if u could guide me for the initial steps to building it maybe

Appreciate the help..
and a really cool plugin

**Comment by don** [comment]
Try https://github.com/don/cordova-hce-demo

**Comment by leftdead7** [comment]
The above link is for the card emulation demo, i meant an demo for the reader application

**Comment by don** [comment]
It should be included in the Android SDK if you downloaded the sample apps. Try this version https://github.com/googlesamples/android-CardReader. Let me know if it works and I'll update the README.

**Comment by leftdead7** [comment]
Yes this looks the same as the reader mentioned in the docs, also it works perfectly well.
The next challenge for me is to implement the  card reader in cordova. Would appreciate some help with that

**Comment by leftdead7** [comment]
Also have one more doubt(not related to this topic) i am unable to add custom plugins to my project after updating to cordova 7. are you aware of this issue

**Comment by sisou** [comment]
@leftdead7 I am currently in the same boat, I want to read HCE cards from a Cordova/Capacitor app. Did you manage to build it 5 years ago?
